CREATE TABLE Client(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(200) NOT NULL CHECK(LENGTH(name)>=3 AND LENGTH(name)<=200)
);

CREATE TABLE Planet(
id VARCHAR(1000) PRIMARY KEY CHECK (id ~ '^[A-Z0-9]+$'),
name VARCHAR(500) NOT NULL CHECK(LENGTH(name)>=1 AND LENGTH(name)<=500)
);

CREATE TABLE Ticket(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
client_id BIGINT,
from_planet_id VARCHAR(1000),
to_planet_id VARCHAR(1000),
CONSTRAINT client_id FOREIGN KEY (client_id) REFERENCES Client (id),
CONSTRAINT from_planet_id FOREIGN KEY (from_planet_id) REFERENCES Planet (id),
CONSTRAINT to_planet_id FOREIGN KEY (to_planet_id) REFERENCES Planet (id)
);
